version: "3.9"
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5051:5051"
    depends_on:
      - storage
    environment:
      - ASPNETCORE_URLS=http://+:5051
      - Storage__Endpoint=http://storage:5050
    volumes:
      - ./frontend-tmp:/tmp
  storage:
    build:
      context: ./
      dockerfile: ./storage/Dockerfile
    ports:
      - "5050:5050"
    environment:
      - ASPNETCORE_URLS=http://+:5050
      - ConnectionString__MySql=server=mysql;user=root;password=${MYSQL_PASSWORD};database=memes
    volumes:
      - storage-tmp:/tmp
  mysql:
    image: docker.io/bitnami/mysql
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
  dotnetmonitor-frontend:
    image: mcr.microsoft.com/dotnet/monitor:6.2.2
    command: --no-auth
    ports:
      - "52333:52333"
      - "52335:52335"
    environment:
      - DOTNET_URLS=http://+:52343
      - DOTNET_Metrics__Endpoints=http://+:52345
    volumes:
      - ./frontend-tmp:/tmp
  dotnetmonitor-storage:
    image: mcr.microsoft.com/dotnet/monitor:6.2.2
    command: --no-auth
    ports:
      - "52343:52343"
      - "52345:52345"
    environment:
      - DOTNET_URLS=http://+:52333
      - DOTNET_Metrics__Endpoints=http://+:52335     
    volumes:
      - storage-tmp:/tmp
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - dotnetmonitor-frontend
      - dotnetmonitor-storage      
volumes:
  mysql_data:
    driver: local
  storage-tmp:
  frontend-tmp:
