version: "3.9"
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5051:5051"
    depends_on:
      - storage
    environment:
      - ASPNETCORE_URLS=http://+:5051
      - OTEL_SERVICE_NAME=frontend
      - Storage__Endpoint=http://storage:5050
      - OtelCollector__Endpoint=http://otelcollector:4318
  storage:
    build:
      context: ./
      dockerfile: ./storage/Dockerfile
    ports:
      - "5050:5050"
    environment:
      - ASPNETCORE_URLS=http://+:5050
      - OTEL_SERVICE_NAME=storage
      - OtelCollector__Endpoint=http://otelcollector:4318
      # for demo purposes only, make sure to pass environment securely
      - ConnectionStrings__MySql=server=mysql;user=root;password=pwd;database=memes
  mysql:
    image: docker.io/bitnami/mysql
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # for demo purposes only, make sure to pass environment securely
      - MYSQL_ROOT_PASSWORD=pwd
  otelcollector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml", "--feature-gates=receiver.dockerstats.useScraperV2"]
    ports:
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14250:14250"
      - "14268:14268"
      - "6831:6831/udp"
      - "16686:16686"
      - "16685:16685"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus-otel.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otelcollector
volumes:
  mysql_data:
    driver: local
