version: "3.9"
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5051:5051"
    depends_on:
      - storage
    cap_add:
      - SYS_PTRACE
    environment:
      - ASPNETCORE_URLS=http://+:5051
      - DOTNET_EnableCrashReport=1
      - DOTNET_DbgEnableMiniDump=1      
    volumes:
      - ./frontend-tmp:/tmp
  storage:
    build:
      context: ./
      dockerfile: ./storage/Dockerfile
    ports:
      - "5050:5050"
    cap_add:
      - SYS_PTRACE
    environment:
      - ASPNETCORE_URLS=http://+:5050
      - DOTNET_EnableCrashReport=1
      - DOTNET_DbgEnableMiniDump=1
    volumes:
      - ./storage-tmp:/tmp
  dotnetmonitor-frontend:
    image: mcr.microsoft.com/dotnet/monitor:6.2.2
    command: --no-auth
    ports:
      - "52333:52333"
      - "52335:52335"
    environment:
      - DOTNET_URLS=http://+:52333
      - DOTNET_Metrics__Endpoints=http://+:52335      
    volumes:
      - ./frontend-tmp:/tmp
  dotnetmonitor-storage:
    image: mcr.microsoft.com/dotnet/monitor:6.2.2
    command: --no-auth
    ports:
      - "52343:52343"
      - "52345:52345"
    environment:
      - DOTNET_URLS=http://+:52343
      - DOTNET_Metrics__Endpoints=http://+:52345     
    volumes:
      - ./storage-tmp:/tmp
volumes:
  frontend_tmp:
  storage_tmp: