apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: awss3
spec:
  type: bindings.aws.s3
  version: v1
  metadata:
  - name: bucket
    secretKeyRef:
      name: awsBucket
      key: awsBucket
  - name: region
    value: us-west-2
  - name: endpoint
    value: s3.us-west-2.amazonaws.com
  - name: accessKey
    secretKeyRef:
      name: awsKey
      key: awsKey
  - name: secretKey
    secretKeyRef:
      name: awsSecret
      key: awsSecret
  - name: decodeBase64
    value: true
  - name: encodeBase64
    value: false
auth:
  secretStore: localsecretstore