scrape_configs:
  - job_name: 'otelcollector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otelcollector:8889']
  - job_name: 'dapr'
    scrape_interval: 10s
    static_configs:
      - targets: ['frontend:9090']
      - targets: ['storage:9090']
